export * from './base/Base.dialog';
export * from './auth/login/Login.dialog';
export * from './users/AddUser.dialog';
export * from './company/AddCompany.dialog';
export * from './orders/OderDetails.dialog';
export * from './product/AddProduct.dialog';
export * from './auth/register/Register.dialog';
export * from './confirm-action/ConfirmAction.dialog';
export * from './auth/Off.disalog';
