# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    networks:
      - default
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE}
    volumes:
      - ./data/postgressql:/var/lib/postgresql/datas
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
  adminer:
    networks:
      - default
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
networks:
  default:
